### PR TITLE
🏗️ Decorate EcPhp CasGuardAuthenticator instead of copy/pasting it

### PR DESCRIPTION
**Pull request by p-bizouard**
Following @drupol recomandations, implementation of a decorator of EcPhp's CasGuardAuthenticator instead of copy/pasting it.

### CODE REVIEW

**Comment by drupol** [comment]
Let me know how it goes !

**Comment by drupol** [comment]
Top!

**Comment by p-bizouard** [comment]
Thank you very much @drupol for your help. I still don't realize someone came from nowhere and gave me advises like you did 🙏

**Comment by drupol** [comment]
That's the beauty of open source ;)

**Pull request merged**
